services:
  backend:
    build:
      context: ./CPanel/backend  # Asegúrate de que esta ruta sea correcta
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
  
  frontend:
    build:
      context: ./CPanel/vite  # Asegúrate de que esta ruta sea correcta
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
  
  database:
    image: postgres:latest
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: users_db
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data