version: '3.8'
services:
  backend:
    build:
      context: ./CPanel/backend  # Cambia esta ruta al directorio de tu backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
    environment:
      - NODE_ENV=production

  frontend:
    build:
      context: ./CPanel/vite  # Cambia esta ruta al directorio de tu frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
    environment:
      - NODE_ENV=production
